// <auto-generated />
using ItaliaTreni.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItaliaTreni.Migrations
{
    [DbContext(typeof(ItaliaTreniContext))]
    [Migration("20240527142235_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItaliaTreni.Models.Measurement", b =>
                {
                    b.Property<int>("mmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mmId"));

                    b.Property<float>("p1")
                        .HasColumnType("real");

                    b.Property<float>("p2")
                        .HasColumnType("real");

                    b.Property<float>("p3")
                        .HasColumnType("real");

                    b.Property<float>("p4")
                        .HasColumnType("real");

                    b.HasKey("mmId");

                    b.ToTable("Measurement");
                });
#pragma warning restore 612, 618
        }
    }
}
